# Generated by Django 5.0.6 on 2024-06-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='image',
            field=models.TextField(verbose_name='Изображение'),
        ),
    ]
